_id: 608bb7901c4a8c002cba4092
title: Match Report
description: Describe your new bucket
icon: receipt
primary: play_count
readOnly: false
history: false
properties:
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
    default: :created_at
  play_count:
    type: number
    title: play_count
    description: Description of the play_count input
    options:
      position: bottom
  arrows_average:
    type: number
    title: arrows_average
    description: Description of the arrows_average input
    options:
      position: bottom
  report_type:
    type: number
    title: report_type
    description: Description of the report_type input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 9
category: Reports
