_id: 6801109ae261c7002d677af3
name: Auto Save Progress
language: javascript
timeout: 195.6
triggers:
  saveProgress:
    type: http
    active: true
    options:
      method: Get
      path: /saveProgress
      preflight: true
env: {}
memoryLimit: 100
