_id: 6576c340afae3f002c09ea30
name: Game League
language: javascript
timeout: 60
triggers:
  onCharged:
    options:
      collection: bucket_61e03400833dac002d229730
      type: INSERT
    type: database
    active: false
  getLeagueParticipantData:
    options:
      method: Get
      path: /getLeagueParticipantData/:msisdn
      preflight: true
    type: http
    active: false
  getChargesByMsisdn:
    options:
      method: Post
      path: /game-league/get-charges
      preflight: true
    type: http
    active: false
  insertFormData:
    options:
      method: Post
      path: /insertFormData
      preflight: true
    type: http
    active: false
  onChargedTvPlus:
    options:
      collection: bucket_61e03400833dac002d229730
      type: INSERT
    type: database
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  DRAW_LOGS_BUCKET: "{DRAW_LOGS_BUCKET}"
  CHARGE_BUCKET: "{CHARGE_BUCKET}"
  GAME_LEAGUE_PARTICIPANTS_BUCKET: "{GAME_LEAGUE_PARTICIPANTS_BUCKET}"
memoryLimit: 100
