_id: 67bf315da35582002bf2bcb7
name: SinglePlay
language: javascript
timeout: 53.7
triggers:
  default:
    type: http
    active: true
    options:
      method: Get
      path: /
      preflight: true
env: {}
memoryLimit: 100
