_id: 633beb26e0b12f002bf611f7
name: Helper
language: javascript
timeout: 34.6
triggers:
  replaceAbusiveName:
    type: schedule
    active: true
    options:
      timezone: UTC
      frequency: 0 * * * *
  getMyIp:
    options:
      method: Get
      path: /getMyIp
      preflight: true
    type: http
    active: true
  buggedUserReward:
    options:
      method: Get
      path: /buggedUserReward
      preflight: true
    type: http
    active: true
  monthlyUniqueUser:
    options:
      method: Get
      path: /monthlyUniqueUser
      preflight: true
    type: http
    active: true
  setFreePlayForAllUsers:
    options:
      method: Get
      path: /setFreePlayForAllUsers
      preflight: true
    type: http
    active: true
  insertUsersChargeCount:
    options:
      method: Get
      path: /insertUsersChargeCount
      preflight: true
    type: http
    active: true
  userChargeCount:
    options:
      method: Get
      path: /userChargeCount
      preflight: true
    type: http
    active: true
  getIdentityTest:
    options:
      method: Get
      path: /getIdentityTest
      preflight: true
    type: http
    active: true
  getPastMatchCount:
    options:
      method: Get
      path: /getPastMatchCount
      preflight: true
    type: http
    active: true
env:
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  USER_BUCKET: "{USER_BUCKET}"
  PAST_MATCHES_BUCKET: "{PAST_MATCHES_BUCKET}"
  GAME_LEAGUE_PARTICIPANTS: "{GAME_LEAGUE_PARTICIPANTS}"
  DRAW_LOGS: "{DRAW_LOGS}"
  CHARGE_BUCKET: "{CHARGE_BUCKET}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
memoryLimit: 100
order: 14
