_id: 637c811506d7ce002c2e43ba
name: Draw Functions
language: javascript
timeout: 60
triggers:
  sendChargeRequest:
    options:
      collection: bucket_61e03400833dac002d229730
      type: INSERT
    type: database
    active: false
env:
  DRAW_LOGS_BUCKET: "{DRAW_LOGS_BUCKET}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
